version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install .[test]

      - run:
          name: 'Check code formatting and do pylinting'
          command: |
            . .virtualenvs/pipelinewise/bin/activate
            pip install unify pylint
            echo "Checking double quotes..."
            find tap_snowflake tests -type f -name '*.py' | xargs unify --check-only
            echo "Running pylint..."
            pylint tap_snowflake tests

      - run:
          name: 'Integration Tests'
          command: |
            . venv/bin/activate
            export LOGGING_CONF_FILE=$(pwd)/sample_logging.conf
            nosetests --where=tests/integration/

workflows:
  version: 2
  build:
    jobs:
      - build